--- 
title: "PA 5928 Data Management & Visualization with R (Spring 2022)"
author: "Tao Tao (University of Minnesota)"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "This is the website for couse PA 5928 in the University of Minnesota"
---

# Course Syllabus

## Course description

Introduction to ``RStudio`` software. Use of ``RStudio`` to carry out ``R`` file and related dataset management functions. Tools and techniques for data analysis and statistical programming in quantitative research or related applied areas. Topics include data selection, data manipulation, and data visualization (including charts, plots, histograms, maps, and other graphs).

## Course prerequisites

Introductory statistics; ability to create bar graphs, line graphs, and scatter plots in MS Excel; and familiarity with principles of data visualization.

## Logistics

**Lecture section**: 2:30 - 3:45 pm Tuesday and Thursday  
**Instructor**: Tao Tao, taotao@umn.edu  
**Location**: HHH 85 Lab  
**Office hour**: 3:45-4:15 Tuesday and Thursday (HHH 295 Cube 2) or by appointment  
**Canvas**: All course notes will be posted in this course website, but links will be updated on Canvas simultaneously. Canvas will also be used to submit your assignments, final project, and grades. Make sure you have enabled the notification of this course on Canvas.

## Course learning outcomes

At the end of this course, students will be able to:

1. Use RStudio to carry out R file and related database management
2. Use R to work with different types of databases and conduct basic data management
3. Use R to visualize data with different types of plots
4. Use R to carry out exploratory data analysis

## Readings
The online note is the main study material in this course.  The course has several supplementary reading materials, which are available on Canvas.  
1. Wickham, H. (2016). *ggplot2: elegant graphics for data analysis*. Springer.  
2. Wickham, H., & Grolemund, G. (2016). *R for data science: import, tidy, transform, visualize, and model data*. O'Reilly Media, Inc.


## Weekly assignment and final project

1. Weekly assignment includes in-class exercise and after-class assignment. Students are required to submit both of them (R codes) with necessary notes.
2. Weekly assignment is always due on next Monday 11:59 pm. *Missing deadline results in a penalty in grades (10% of the total grades for each 24 hours, less than 24 hours will be counted as 24 hours)*. Check your files before submission. *Wrong submission results in a penalty in grades (20% of the total grades)*.
3. Students will use the knowledge from this course to complete a final project (data analysis for a interested research question and make a poster to show off their work). You can find the description of the final project in the chapter of [final project](./final-project.html)).  
4. Grading policy

* Weekly assignment: 70%
* Final project: 30%

Weekly assignment grading rubric

| Requirements                                                                             | Grades |
|------------------------------------------------------------------------------------------|:------:|
| Codes could generate the results required by the problems                                | 6      |
| Necessary notes to indicate the general idea (usage, function, purpose, or mechanism)    | 3      |
| Codes and notes are neat and well-organized                                              | 1      |

## Course schedule

| Week       | Date   | Topic                                         |
|------------|--------|-----------------------------------------------|
| Week 1 Tue | Mar 15 | **Course introduction + Introduction to RStudio** |
| Week 1 Thu | Mar 17 | **Introduction to R**                             |
| Week 2 Tue | Mar 22 | **Data manipulation with base functions**         |
| Week 2 Thu | Mar 24 | **Data manipulation with dplyr Part I**           |
| Week 3 Tue | Mar 29 | **Data manipulation with dplyr Part II**          |
| Week 3 Thu | Mar 31 | **[Zoom] Using IPUMS data in R with ipumsr (Guest speakers: Derek Burk, Dan Ehrlich, and Kara Fisher)**          |
| Week 4 Tue | Apr 5 | **Data visualization with base functions**        |
| Week 4 Thu | Apr 7  | **Data visualization with ggplot2 Part I**        |
| Week 6 Tue | Apr 12 | **Data visualization with ggplot2 Part II**       |
| Week 6 Thu | Apr 14 | **Data visualization with ggplot2 Part III**      |
| Week 7 Tue | Apr 19 | **Simple statistics in R Part I**                 |
| Week 7 Thu | Apr 21 | **Simple statistics in R Part II**                |
| Week 8 Tue | Apr 26 | **Exploratory Data Analysis Part I**              |
| Week 8 Thu | Apr 28 | **Exploratory Data Analysis Part II**             |

## Homework and projects collaboration and submission policy

1. **Students can discuss their works with other students, but must code and write up notes by themselves. [Plagiarism](https://communitystandards.umn.edu/content/plagiarism) is not allowed by the university policies. Please do be careful about this.**
2. Weekly assignments and projects should be submitted through Canvas.
3. If you cannot attend the class, please write an email to the instructor including a valid reason before the class. In this case, the instructor will use zoom to record the class and share the recordings with the students who are absent or can only attend online. However, the focus of this course is still on the in-person class (except one guest speaker lecture).
4. When you communicate the instructor with emails, please include ``PA 5928`` at the beginning of your title.

## Univeristy policies

### Safe Campus COVID-19 Response

The University of Minnesota currently requires all students, staff, and faculty to wear masks when indoors regardless of vaccination status.  Students are recommended to sit in the same seat throughout the course to enhance contact tracing should it be necessary.  Please do not eat in the classroom and lab; it is fine to drink water occasionally.  Please stay at home if you experience symptoms of COVID-19 and consult with your healthcare provider about an appropriate course of action. An absence due to symptoms of COVID-19 is an excused absence, and I will work with you to find the best course of action for missed work and/or class experiences.

https://safe-campus.umn.edu/return-campus/covid-19-updates

### Student Conduct Code

The University seeks an environment that promotes academic achievement and integrity, that is protective of free inquiry, and that serves the educational mission of the University. Similarly, the University seeks a community that is free from violence, threats, and intimidation; that is respectful of the rights, opportunities, and welfare of students, faculty, staff, and guests of the University; and that does not threaten the physical or mental health or safety of members of the University community.  
As a student at the University you are expected to adhere to Board of Regents Policy: Student Conduct Code. To review the Student Conduct Code, please see:   https://regents.umn.edu/sites/regents.umn.edu/files/2019-09/policy_student_conduct_code.pdf  
Note that the conduct code specifically addresses disruptive classroom conduct, which means "engaging in behavior that substantially or repeatedly interrupts either the instructor's ability to teach  and/or a student’s ability to learn.” The classroom extends to any setting where a student is engaged in work toward academic credit or satisfaction of program-based requirements or related activities.

### Scholastic Dishonesty

You are expected to do your own academic work and cite sources as necessary. Failing to do so is scholastic dishonesty. Scholastic dishonesty means plagiarizing; cheating on assignments or examinations; engaging in unauthorized collaboration on academic work; taking, acquiring, or using test materials without faculty permission; submitting false or incomplete records of academic achievement; acting alone or in cooperation with another to falsify records or to obtain dishonestly grades, honors, awards, or professional endorsement; altering, forging, or misusing a University academic record; or fabricating or falsifying data, research procedures, or data analysis. (Student Conduct Code: https://regents.umn.edu/sites/regents.umn.edu/files/2019-09/policy_student_conduct_code.pdf) If it is determined that a student has cheated, the student may be given an "F" or an "N" for the course, and may face additional sanctions from the University. For additional information, please see: https://policy.umn.edu/education/instructorresp.

### Sexual harassment, sexual assault, stalking and relationship violence

The University prohibits sexual misconduct, and encourages anyone experiencing sexual misconduct to access resources for personal support and reporting. If you want to speak confidentially with someone about an experience of sexual misconduct, please contact your campus resources including the Aurora Center, Boynton Mental Health or Student Counseling Services (https://eoaa.umn.edu/report-misconduct). If you want to report sexual misconduct, or have questions about the University’s policies and procedures related to sexual misconduct, please contact your campus Title IX office or relevant policy contacts.  
Instructors are required to share information they learn about possible sexual misconduct with the campus Title IX office that addresses these concerns. This allows a Title IX staff member to reach out to those who have experienced sexual misconduct to provide information about personal support resources and options for investigation. You may talk to instructors about concerns related to sexual misconduct, and they will provide support and keep the information you share private to the extent possible given their University role.  
https://regents.umn.edu/sites/regents.umn.edu/files/2019-09/policy_sexual_harassment_sexual_assault_stalking_and_relationship_violence.pdf

### Equity, Diversity, Equal Opportunity, and Affirmative Action

The University provides equal access to and opportunity in its programs and facilities, without regard to race, color, creed, religion, national origin, gender, age, marital status, disability, public assistance status, membership or activity in a local commission created for the purpose of dealing with discrimination, veteran status, sexual orientation, gender identity, or gender expression. For more information, please consult Board of Regents Policy: https://regents.umn.edu/sites/regents.umn.edu/files/2019-09/policy_equity_diversity_equal_opportunity_and_affirmative_action.pdf.

### Disability Accommodations

The University views disability as an important aspect of diversity, and is committed to providing equitable access to learning opportunities for all students. The Disability Resource Center (DRC) is the campus office that collaborates with students who have disabilities to provide and/or arrange reasonable accommodations.

* If you have, or think you have, a disability in any area such as, mental health, attention, learning, chronic health, sensory, or physical, please contact the DRC office on your campus (UM Twin Cities - 626.1333) to arrange a confidential discussion regarding equitable access and reasonable accommodations.
* Students with short-term disabilities, such as a broken arm, can often work with instructors to minimize classroom barriers. In situations where additional assistance is needed, students should contact the DRC as noted above.
* If you are registered with the DRC and have a disability accommodation letter dated for this semester or this year, please contact your instructor early in the semester to review how the accommodations will be applied in the course.
* If you are registered with the DRC and have questions or concerns about your accommodations please contact your (access consultant/disability specialist).

### Mental Health and Stress Management

As a student you may experience a range of issues that can cause barriers to learning, such as strained relationships, increased anxiety, alcohol/drug problems, feeling down, difficulty concentrating and/or lack of motivation. These mental health concerns or stressful events may lead to diminished academic performance and may reduce your ability to participate in daily activities. University services are available to assist you. You can learn more about the broad range of confidential mental health services available on campus via the Student Mental Health Website: http://www.mentalhealth.umn.edu.


### Tennessen Warning Notice Pursuant to MN Department of Administration’s Data Practices

To make this class more accessible to all enrolled students, we intend to record all class lectures and discussions.  Since your audio/video may be part of those recordings we are informing you.  Along with the instructor and teaching assistants, these recordings will be shared with only the students enrolled in the class during this semester, in accordance with FERPA regulations.

### Other university policies

https://docs.google.com/document/d/1VT-E1dzn-HZbRII3GXvJ48EA8UAbu84wwDTTGDRhb2g/edit#heading=h.rlwkd6rie2v6
